version: '3'

services:
  master:
    image: actionml/spark:latest
    command: master
    ports:
      - 8080:8080

  worker-1:
    image: actionml/spark:latest
    command: worker spark://master:7077
    depends_on:
      - master
    ports:
      - 8081:8081
    environment:
      - SPARK_WORKER_MEMORY=1g
  worker-2:
    image: actionml/spark:latest
    command: worker spark://master:7077
    depends_on:
      - master
    ports:
      - 8082:8082
    environment:
      - SPARK_WORKER_MEMORY=1g
  worker-3:
    image: actionml/spark:latest
    command: worker spark://master:7077
    depends_on:
      - master
    ports:
      - 8083:8083
    environment:
      - SPARK_WORKER_MEMORY=1g
